import { type EditorThemeClasses } from "lexical";

import "./editor-theme.css";

export const editorTheme: EditorThemeClasses = {
  ltr: "text-left",
  rtl: "text-right",
  heading: {
    h1: "scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl",
    h2: "scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0",
    h3: "scroll-m-20 text-2xl font-semibold tracking-tight",
    h4: "scroll-m-20 text-xl font-semibold tracking-tight",
    h5: "scroll-m-20 text-lg font-semibold tracking-tight",
    h6: "scroll-m-20 text-base font-semibold tracking-tight",
  },
  paragraph: "leading-7 [&:not(:first-child)]:mt-4",
  quote: "mt-4 border-l-2 pl-6 italic text-muted-foreground",
  link: "text-primary underline underline-offset-4 hover:cursor-pointer",
  list: {
    checklist: "my-2 p-0 list-none",
    listitem: "my-1 text-sm leading-normal",
    listitemChecked:
        'relative my-1 px-6 list-none outline-none line-through text-muted-foreground before:content-[""] before:w-4 before:h-4 before:top-0.5 before:left-0 before:cursor-pointer before:block before:absolute before:border before:border-primary before:rounded before:bg-primary after:content-[""] after:cursor-pointer after:border-primary-foreground after:border-solid after:absolute after:block after:top-[5px] after:w-[4px] after:left-[6px] after:h-[7px] after:rotate-45 after:border-r-2 after:border-b-2 after:border-l-0 after:border-t-0',
    listitemUnchecked:
        'relative my-1 px-6 list-none outline-none before:content-[""] before:w-4 before:h-4 before:top-0.5 before:left-0 before:cursor-pointer before:block before:absolute before:border before:border-input before:rounded bg-background',
    nested: {
      listitem: "list-none my-1",
    },
    ol: "my-2 pl-6 list-decimal space-y-1",
    olDepth: [
      "!list-decimal",
      "!list-[upper-roman]",
      "!list-[lower-roman]",
      "!list-[upper-alpha]",
      "!list-[lower-alpha]",
    ],
    ul: "my-2 pl-6 list-disc space-y-1",
    ulDepth: [
      "!list-disc",
      "!list-[circle]",
      "!list-[square]",
      "!list-disc",
      "!list-[circle]",
    ],
  },
  hashtag: "text-primary bg-primary/10 rounded-md px-1",
  text: {
    bold: "font-bold",
    code: "bg-muted text-foreground px-1.5 py-0.5 rounded-md font-mono text-[0.875em]",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "sub text-xs",
    superscript: "sup text-xs",
    underline: "underline",
    underlineStrikethrough: "[text-decoration:underline_line-through]",
  },
  image: "relative inline-block user-select-none cursor-default editor-image",
  inlineImage:
      "relative inline-block user-select-none cursor-default inline-editor-image",
  keyword: "text-accent-foreground bg-accent rounded-sm px-1 font-semibold",
  code: "EditorTheme__code",
  codeHighlight: {
    atrule: "EditorTheme__tokenAttr",
    attr: "EditorTheme__tokenAttr",
    boolean: "EditorTheme__tokenProperty",
    builtin: "EditorTheme__tokenSelector",
    cdata: "EditorTheme__tokenComment",
    char: "EditorTheme__tokenSelector",
    class: "EditorTheme__tokenFunction",
    "class-name": "EditorTheme__tokenFunction",
    comment: "EditorTheme__tokenComment",
    constant: "EditorTheme__tokenProperty",
    deleted: "EditorTheme__tokenProperty",
    doctype: "EditorTheme__tokenComment",
    entity: "EditorTheme__tokenOperator",
    function: "EditorTheme__tokenFunction",
    important: "EditorTheme__tokenVariable",
    inserted: "EditorTheme__tokenSelector",
    keyword: "EditorTheme__tokenAttr",
    namespace: "EditorTheme__tokenVariable",
    number: "EditorTheme__tokenProperty",
    operator: "EditorTheme__tokenOperator",
    prolog: "EditorTheme__tokenComment",
    property: "EditorTheme__tokenProperty",
    punctuation: "EditorTheme__tokenPunctuation",
    regex: "EditorTheme__tokenVariable",
    selector: "EditorTheme__tokenSelector",
    string: "EditorTheme__tokenSelector",
    symbol: "EditorTheme__tokenProperty",
    tag: "EditorTheme__tokenProperty",
    url: "EditorTheme__tokenOperator",
    variable: "EditorTheme__tokenVariable",
  },
  characterLimit: "!bg-destructive/50",
  table: "EditorTheme__table w-full border-collapse my-4",
  tableCell: "EditorTheme__tableCell border px-4 py-2 text-left relative",
  tableCellActionButton:
      "EditorTheme__tableCellActionButton bg-background border rounded-full w-5 h-5 text-foreground cursor-pointer flex items-center justify-center",
  tableCellActionButtonContainer:
      "EditorTheme__tableCellActionButtonContainer block right-1 top-1.5 absolute z-10 w-5 h-5",
  tableCellEditing: "EditorTheme__tableCellEditing rounded-sm shadow-sm",
  tableCellHeader:
      "EditorTheme__tableCellHeader bg-muted border px-4 py-2 text-left font-bold",
  tableCellPrimarySelected:
      "EditorTheme__tableCellPrimarySelected border-2 border-primary absolute -left-[1px] -top-[1px] z-10 w-[calc(100%+2px)] h-[calc(100%+2px)] pointer-events-none",
  tableCellResizer:
      "EditorTheme__tableCellResizer absolute -right-1 h-full w-2 cursor-ew-resize z-10 top-0",
  tableCellSelected: "EditorTheme__tableCellSelected bg-muted/50",
  tableCellSortedIndicator:
      "EditorTheme__tableCellSortedIndicator block opacity-50 absolute bottom-0 left-0 w-full h-1 bg-muted",
  tableResizeRuler:
      "EditorTheme__tableCellResizeRuler block absolute w-[1px] h-full bg-primary top-0",
  tableRowStriping: "EditorTheme__tableRowStriping even:bg-muted/30",
  tableSelected: "EditorTheme__tableSelected ring-2 ring-primary",
  tableSelection: "EditorTheme__tableSelection bg-transparent",
  layoutItem: "border border-dashed px-4 py-2 rounded-md",
  layoutContainer: "grid gap-2.5 my-2.5 mx-0",
  autocomplete: "text-muted-foreground",
  blockCursor: "",
  embedBlock: {
    base: "user-select-none",
    focus: "ring-2 ring-primary ring-offset-2",
  },
  hr: "p-0 border-none my-4 cursor-pointer after:content-[''] after:block after:h-px after:bg-border selected:ring-2 selected:ring-primary",
  indent: "pl-6",
  mark: "",
  markOverlap: "",
};